import * as fs from 'fs';
import * as path from 'path';
import type { FileRecord, FileExtraction, MonorepoPackage, PhaseProgressEvent } from '@geodesic/types';

// Files larger than this treated as data files and characterize-only (not raw dump)
const DATA_FILE_THRESHOLD_BYTES = 1_000_000;
// Config/schema/docs content capped at this to avoid pathological memory use
const CONTENT_CAP_BYTES = 512_000;
// Lines to sample for data file characterization
const DATA_SAMPLE_LINES = 50;
const DATA_TAIL_LINES = 20;

const GENERATED_MARKERS = [
  '@generated', '@auto-generated', 'DO NOT EDIT', 'Do not edit',
  'Code generated by', 'This file was automatically generated',
  'AUTO-GENERATED FILE', 'auto-generated', 'generated by',
];

const GENERATED_DIRS = new Set(['generated', '__generated__', 'codegen', 'gen', '.gen']);

const DATA_EXTENSIONS = new Set([
  '.log', '.csv', '.tsv', '.ndjson', '.jsonl', '.dump', '.bak', '.backup',
  '.bin', '.dat', '.db', '.sqlite', '.sqlite3',
]);

const BINARY_EXTENSIONS = new Set([
  '.png', '.jpg', '.jpeg', '.gif', '.webp', '.avif', '.ico', '.svg',
  '.woff', '.woff2', '.ttf', '.otf', '.eot',
  '.mp4', '.mp3', '.wav', '.ogg', '.webm',
  '.zip', '.tar', '.gz', '.bz2', '.7z', '.rar',
  '.pdf', '.docx', '.xlsx', '.pptx',
  '.exe', '.dll', '.so', '.dylib', '.wasm',
  '.lock', // lockfiles — handled separately
]);

const LOCKFILE_NAMES = new Set([
  'package-lock.json', 'yarn.lock', 'pnpm-lock.yaml',
  'Pipfile.lock', 'poetry.lock', 'Gemfile.lock', 'Cargo.lock',
  'composer.lock', 'go.sum',
]);

const SCHEMA_EXTENSIONS = new Set(['.prisma', '.sql', '.graphql', '.gql', '.proto']);
const SCHEMA_FILE_PATTERNS = [/^schema\./i, /^models\./i, /^types\./i];
const SCHEMA_DIRS = new Set(['prisma', 'migrations', 'db', 'database', 'schema']);

const ENV_FILE_PATTERN = /^\.env(\.|$)/;

const CONFIG_EXTENSIONS = new Set([
  '.json', '.yaml', '.yml', '.toml', '.ini', '.cfg', '.conf', '.config',
  '.properties', '.xml',
]);

const SOURCE_EXTENSIONS = new Set([
  '.ts', '.tsx', '.js', '.mjs', '.cjs', '.jsx',
  '.py', '.go', '.rs', '.java', '.kt', '.kts',
  '.rb', '.php', '.cs', '.swift',
  '.sh', '.bash',
]);

const DOC_EXTENSIONS = new Set(['.md', '.mdx', '.rst', '.txt', '.adoc']);

// ─── Binary Detection ─────────────────────────────────────────────────────────

function isBinaryBuffer(buf: Buffer): boolean {
  const sampleSize = Math.min(buf.length, 8000);
  let nullCount = 0;
  for (let i = 0; i < sampleSize; i++) {
    if (buf[i] === 0) nullCount++;
  }
  return nullCount / sampleSize > 0.01;
}

function readFileAsText(filePath: string): { text: string; error: null } | { text: null; error: string } {
  let buf: Buffer;
  try {
    buf = fs.readFileSync(filePath);
  } catch (err) {
    return { text: null, error: err instanceof Error ? err.message : String(err) };
  }

  if (isBinaryBuffer(buf)) {
    return { text: null, error: 'binary' };
  }

  try {
    return { text: buf.toString('utf8'), error: null };
  } catch {
    return { text: buf.toString('latin1'), error: null };
  }
}

// ─── File Type Classification ─────────────────────────────────────────────────

function isGeneratedPath(relativePath: string): boolean {
  const parts = relativePath.split('/');
  return parts.some(p => GENERATED_DIRS.has(p));
}

function detectGeneratedMarker(firstLines: string): { isGenerated: true; marker: string } | { isGenerated: false } {
  for (const marker of GENERATED_MARKERS) {
    if (firstLines.includes(marker)) return { isGenerated: true, marker };
  }
  return { isGenerated: false };
}

function detectGenerator(relativePath: string, firstLines: string): string | null {
  if (firstLines.includes('prisma')) return 'Prisma';
  if (firstLines.includes('graphql-codegen') || firstLines.includes('GraphQL Code Generator')) return 'GraphQL Codegen';
  if (firstLines.includes('openapi-generator') || firstLines.includes('OpenAPI Generator')) return 'OpenAPI Generator';
  if (firstLines.includes('protoc')) return 'Protobuf';
  if (relativePath.endsWith('.d.ts')) return 'TypeScript Declaration';
  return null;
}

function isSchemaFile(relativePath: string, name: string): boolean {
  const ext = path.extname(name).toLowerCase();
  if (SCHEMA_EXTENSIONS.has(ext)) return true;
  if (SCHEMA_FILE_PATTERNS.some(p => p.test(name))) return true;
  const parts = relativePath.split('/');
  return parts.some(p => SCHEMA_DIRS.has(p));
}

function classifyFile(
  relativePath: string,
  name: string,
  sizeBytes: number,
  language: string | null,
): 'source' | 'config' | 'schema' | 'env' | 'lockfile' | 'docs' | 'script' | 'binary' | 'generated_candidate' | 'data' {
  const ext = path.extname(name).toLowerCase();

  if (LOCKFILE_NAMES.has(name)) return 'lockfile';
  if (ENV_FILE_PATTERN.test(name)) return 'env';
  if (BINARY_EXTENSIONS.has(ext)) return 'binary';
  if (DATA_EXTENSIONS.has(ext)) return 'data';
  if (isSchemaFile(relativePath, name)) return 'schema';
  if (DOC_EXTENSIONS.has(ext)) return 'docs';
  if (ext === '.sh' || ext === '.bash' || name === 'Makefile' || name === 'Dockerfile') return 'script';
  if (SOURCE_EXTENSIONS.has(ext) || (language !== null && language !== 'JSON' && language !== 'YAML' && language !== 'TOML')) return 'source';
  if (CONFIG_EXTENSIONS.has(ext)) return 'config';

  // Large files with no recognized source extension → data
  if (sizeBytes > DATA_FILE_THRESHOLD_BYTES) return 'data';

  return 'source';
}

// ─── Source Extraction ────────────────────────────────────────────────────────

const TS_EXPORT = /^export\s+(?:default\s+)?(?:async\s+)?(?:function|class|const|let|var|interface|type|enum|abstract\s+class)\s+(\w+)/;
const TS_EXPORT_DEFAULT = /^export\s+default\s+/;
const TS_MODULE_EXPORTS = /^module\.exports\s*=/;
const TS_IMPORT_FROM = /^(?:import|export)\s+.*from\s+['"]([^'"]+)['"]/;
const TS_REQUIRE = /\brequire\s*\(\s*['"]([^'"]+)['"]\s*\)/g;
const TS_FUNCTION = /^(?:export\s+)?(?:async\s+)?function\s+(\w+)\s*\(/;
const TS_ARROW = /^(?:export\s+)?(?:const|let)\s+(\w+)\s*=\s*(?:async\s*)?\(/;
const TS_CLASS = /^(?:export\s+)?(?:abstract\s+)?class\s+(\w+)/;
const TS_DECORATOR = /^\s*@(\w+)/;

const PY_DEF = /^(?:async\s+)?def\s+(\w+)\s*\(/;
const PY_CLASS = /^class\s+(\w+)/;
const PY_IMPORT = /^(?:import\s+(\S+)|from\s+(\S+)\s+import)/;
const PY_DECORATOR = /^\s*@(\w+)/;

const GO_FUNC = /^func\s+(?:\(\w+\s+[*]?\w+\)\s+)?(\w+)\s*\(/;
const GO_TYPE = /^type\s+(\w+)\s+/;
const GO_IMPORT_PATH = /^\s+"([^"]+)"/;

const JAVA_CLASS = /^(?:public\s+|private\s+|protected\s+)?(?:abstract\s+)?(?:class|interface|enum)\s+(\w+)/;
const JAVA_METHOD = /^\s+(?:public|private|protected)\s+(?:static\s+)?(?:\w+(?:<[^>]+>)?)\s+(\w+)\s*\(/;

function extractSource(content: string, language: string | null): FileExtraction {
  const lines = content.split('\n');
  const exports: string[] = [];
  const imports: string[] = [];
  const functions: string[] = [];
  const classes: string[] = [];
  const decorators: string[] = [];
  let hasDefaultExport = false;

  const lang = language ?? '';

  if (lang === 'TypeScript' || lang === 'JavaScript') {
    for (const line of lines) {
      const trimmed = line.trim();
      if (!trimmed) continue;

      const exportMatch = TS_EXPORT.exec(trimmed);
      if (exportMatch?.[1]) exports.push(exportMatch[1]);

      if (TS_EXPORT_DEFAULT.test(trimmed)) hasDefaultExport = true;
      if (TS_MODULE_EXPORTS.test(trimmed)) hasDefaultExport = true;

      const importMatch = TS_IMPORT_FROM.exec(trimmed);
      if (importMatch?.[1]) imports.push(importMatch[1]);

      let reqMatch: RegExpExecArray | null;
      const reqLine = trimmed;
      TS_REQUIRE.lastIndex = 0;
      while ((reqMatch = TS_REQUIRE.exec(reqLine)) !== null) {
        if (reqMatch[1]) imports.push(reqMatch[1]);
      }

      const fnMatch = TS_FUNCTION.exec(trimmed);
      if (fnMatch?.[1]) functions.push(fnMatch[1]);

      const arrowMatch = TS_ARROW.exec(trimmed);
      if (arrowMatch?.[1]) functions.push(arrowMatch[1]);

      const classMatch = TS_CLASS.exec(trimmed);
      if (classMatch?.[1]) classes.push(classMatch[1]);

      const decMatch = TS_DECORATOR.exec(trimmed);
      if (decMatch?.[1]) decorators.push(decMatch[1]);
    }

  } else if (lang === 'Python') {
    for (const line of lines) {
      const trimmed = line.trim();
      if (!trimmed) continue;

      const defMatch = PY_DEF.exec(trimmed);
      if (defMatch?.[1]) {
        functions.push(defMatch[1]);
        if (!defMatch[1].startsWith('_')) exports.push(defMatch[1]);
      }

      const classMatch = PY_CLASS.exec(trimmed);
      if (classMatch?.[1]) {
        classes.push(classMatch[1]);
        if (!classMatch[1].startsWith('_')) exports.push(classMatch[1]);
      }

      const importMatch = PY_IMPORT.exec(trimmed);
      if (importMatch) imports.push(importMatch[1] ?? importMatch[2] ?? '');

      const decMatch = PY_DECORATOR.exec(trimmed);
      if (decMatch?.[1]) decorators.push(decMatch[1]);
    }

  } else if (lang === 'Go') {
    let inImportBlock = false;
    for (const line of lines) {
      const trimmed = line.trim();
      if (trimmed === 'import (') { inImportBlock = true; continue; }
      if (inImportBlock && trimmed === ')') { inImportBlock = false; continue; }
      if (inImportBlock) {
        const ipMatch = GO_IMPORT_PATH.exec(line);
        if (ipMatch?.[1]) imports.push(ipMatch[1]);
        continue;
      }
      if (trimmed.startsWith('import "')) {
        const m = /"([^"]+)"/.exec(trimmed);
        if (m?.[1]) imports.push(m[1]);
      }
      const fnMatch = GO_FUNC.exec(trimmed);
      if (fnMatch?.[1]) {
        functions.push(fnMatch[1]);
        if (/^[A-Z]/.test(fnMatch[1])) exports.push(fnMatch[1]);
      }
      const typeMatch = GO_TYPE.exec(trimmed);
      if (typeMatch?.[1]) {
        classes.push(typeMatch[1]);
        if (/^[A-Z]/.test(typeMatch[1])) exports.push(typeMatch[1]);
      }
    }

  } else if (lang === 'Java' || lang === 'Kotlin') {
    for (const line of lines) {
      const trimmed = line.trim();
      const classMatch = JAVA_CLASS.exec(trimmed);
      if (classMatch?.[1]) { classes.push(classMatch[1]); exports.push(classMatch[1]); }
      const methodMatch = JAVA_METHOD.exec(trimmed);
      if (methodMatch?.[1]) functions.push(methodMatch[1]);
      if (trimmed.startsWith('import ')) {
        const parts = trimmed.split(' ');
        if (parts[1]) imports.push(parts[1].replace(';', ''));
      }
      const decMatch = TS_DECORATOR.exec(trimmed);
      if (decMatch?.[1]) decorators.push(decMatch[1]);
    }

  } else if (lang === 'Ruby') {
    for (const line of lines) {
      const trimmed = line.trim();
      if (trimmed.startsWith('def ') || trimmed.startsWith('def self.')) {
        const name = trimmed.replace(/^def\s+(?:self\.)?/, '').split(/[\s(]/)[0];
        if (name) functions.push(name);
      }
      if (trimmed.startsWith('class ') || trimmed.startsWith('module ')) {
        const name = trimmed.split(' ')[1];
        if (name) classes.push(name);
      }
      if (trimmed.startsWith('require ') || trimmed.startsWith('require_relative ')) {
        const m = /['"]([^'"]+)['"]/.exec(trimmed);
        if (m?.[1]) imports.push(m[1]);
      }
    }
  }

  // Deduplicate
  return {
    type: 'source',
    exports: [...new Set(exports)].slice(0, 200),
    imports: [...new Set(imports)].slice(0, 200),
    functions: [...new Set(functions)].slice(0, 200),
    classes: [...new Set(classes)].slice(0, 100),
    decorators: [...new Set(decorators)].slice(0, 100),
    hasDefaultExport,
  };
}

// ─── Data Characterization ────────────────────────────────────────────────────

function detectDataFormat(ext: string, firstLines: string): string {
  if (ext === '.log' || /\d{4}-\d{2}-\d{2}T\d{2}:\d{2}/.test(firstLines)) return 'log';
  if (ext === '.csv' || ext === '.tsv') return ext === '.csv' ? 'csv' : 'tsv';
  if (ext === '.jsonl' || ext === '.ndjson') return 'ndjson';
  if (ext === '.sql' || firstLines.includes('INSERT INTO') || firstLines.includes('CREATE TABLE')) return 'sql-dump';
  if (ext === '.xml') return 'xml';
  if (firstLines.trim().startsWith('{') || firstLines.trim().startsWith('[')) return 'json-data';
  if (ext === '.dump' || ext === '.bak' || ext === '.backup') return 'backup';
  if (ext === '.db' || ext === '.sqlite' || ext === '.sqlite3') return 'sqlite';
  return 'unknown';
}

function characterizeData(content: string, ext: string): { detectedFormat: string; characterization: string } {
  const lines = content.split('\n');
  const head = lines.slice(0, DATA_SAMPLE_LINES).join('\n');
  const tail = lines.slice(-DATA_TAIL_LINES).join('\n');
  const characterization = head + (lines.length > DATA_SAMPLE_LINES + DATA_TAIL_LINES ? '\n...\n' + tail : '');
  return { detectedFormat: detectDataFormat(ext, head), characterization };
}

// ─── Lockfile Extraction ──────────────────────────────────────────────────────

function extractLockfile(name: string, content: string): FileExtraction {
  const formatMap: Record<string, string> = {
    'package-lock.json': 'npm', 'yarn.lock': 'yarn', 'pnpm-lock.yaml': 'pnpm',
    'Pipfile.lock': 'pipenv', 'poetry.lock': 'poetry', 'Gemfile.lock': 'bundler',
    'Cargo.lock': 'cargo', 'composer.lock': 'composer', 'go.sum': 'go',
  };
  const lockfileFormat = formatMap[name] ?? 'unknown';
  // Count dependency entries by counting unique version/resolved lines
  const depCount = (content.match(/^\s+"?version"?:/gm) ?? []).length ||
                   (content.match(/^[a-zA-Z@]/gm) ?? []).length;
  return { type: 'lockfile', dependencyCount: depCount, lockfileFormat };
}

// ─── Binary Format Detection ──────────────────────────────────────────────────

function detectBinaryFormat(ext: string): string {
  const map: Record<string, string> = {
    '.png': 'image/png', '.jpg': 'image/jpeg', '.jpeg': 'image/jpeg',
    '.gif': 'image/gif', '.webp': 'image/webp', '.ico': 'image/x-icon',
    '.svg': 'image/svg+xml', '.avif': 'image/avif',
    '.woff': 'font/woff', '.woff2': 'font/woff2', '.ttf': 'font/ttf', '.otf': 'font/otf',
    '.mp4': 'video/mp4', '.mp3': 'audio/mp3', '.wav': 'audio/wav',
    '.pdf': 'application/pdf', '.zip': 'application/zip',
    '.tar': 'application/tar', '.gz': 'application/gzip',
    '.exe': 'application/executable', '.dll': 'application/dll',
    '.wasm': 'application/wasm', '.so': 'application/shared-lib',
  };
  return map[ext] ?? 'application/octet-stream';
}

// ─── Main Reader ──────────────────────────────────────────────────────────────

export interface FileReadCounts {
  binaryFiles: number;
  generatedFiles: number;
  dataFiles: number;
  errorFiles: number;
}

export function readAllFiles(
  repoPath: string,
  fileRecords: Record<string, FileRecord>,
  monorepoPackages: MonorepoPackage[],
  onEvent: (e: PhaseProgressEvent) => void,
): FileReadCounts {
  const counts: FileReadCounts = { binaryFiles: 0, generatedFiles: 0, dataFiles: 0, errorFiles: 0 };
  const paths = Object.keys(fileRecords);
  const total = paths.length;
  let done = 0;

  for (const relativePath of paths) {
    const record = fileRecords[relativePath];
    if (!record || record.isSymlink) {
      done++;
      continue;
    }

    const fullPath = path.join(repoPath, ...relativePath.split('/'));
    const ext = path.extname(record.name).toLowerCase();
    const baseClass = classifyFile(relativePath, record.name, record.sizeBytes, record.language);
    done++;

    // Binary by extension — no read needed
    if (baseClass === 'binary') {
      const extraction: FileExtraction = { type: 'binary', detectedFormat: detectBinaryFormat(ext) };
      fileRecords[relativePath] = { ...record, extraction };
      counts.binaryFiles++;
      onEvent({ type: 'file_read', phase: 2, message: `binary: ${relativePath}`, filePath: relativePath, count: done, total });
      continue;
    }

    // Lockfiles — read for summary, not content storage
    if (baseClass === 'lockfile') {
      const result = readFileAsText(fullPath);
      if (result.error !== null) {
        fileRecords[relativePath] = { ...record, extraction: { type: 'error', message: result.error, code: null } };
        counts.errorFiles++;
      } else {
        fileRecords[relativePath] = { ...record, extraction: extractLockfile(record.name, result.text) };
      }
      onEvent({ type: 'file_read', phase: 2, message: `lockfile: ${relativePath}`, filePath: relativePath, count: done, total });
      continue;
    }

    // Env files — keys only
    if (baseClass === 'env') {
      const result = readFileAsText(fullPath);
      if (result.error !== null) {
        fileRecords[relativePath] = { ...record, extraction: { type: 'error', message: result.error, code: null } };
        counts.errorFiles++;
      } else {
        const keys = result.text.split('\n')
          .map(l => l.trim())
          .filter(l => l && !l.startsWith('#') && l.includes('='))
          .map(l => l.split('=')[0]?.trim() ?? '')
          .filter(Boolean);
        const hasRealValues = result.text.split('\n')
          .some(l => {
            const eq = l.indexOf('=');
            if (eq === -1) return false;
            const val = l.slice(eq + 1).trim();
            return val.length > 0 && val !== '""' && val !== "''" && !val.startsWith('#');
          });
        fileRecords[relativePath] = { ...record, extraction: { type: 'env', keys, hasRealValues } };
      }
      onEvent({ type: 'file_read', phase: 2, message: `env: ${relativePath}`, filePath: relativePath, count: done, total });
      continue;
    }

    // Data files — characterize only
    if (baseClass === 'data' || record.sizeBytes > DATA_FILE_THRESHOLD_BYTES) {
      const result = readFileAsText(fullPath);
      if (result.error === 'binary') {
        fileRecords[relativePath] = { ...record, extraction: { type: 'binary', detectedFormat: detectBinaryFormat(ext) } };
        counts.binaryFiles++;
      } else if (result.error !== null) {
        fileRecords[relativePath] = { ...record, extraction: { type: 'error', message: result.error, code: null } };
        counts.errorFiles++;
      } else {
        const { detectedFormat, characterization } = characterizeData(result.text, ext);
        fileRecords[relativePath] = { ...record, extraction: { type: 'data', detectedFormat, characterization } };
        counts.dataFiles++;
      }
      onEvent({ type: 'file_read', phase: 2, message: `data: ${relativePath}`, filePath: relativePath, count: done, total });
      continue;
    }

    // All remaining files: read fully
    const result = readFileAsText(fullPath);
    if (result.error === 'binary') {
      fileRecords[relativePath] = { ...record, extraction: { type: 'binary', detectedFormat: detectBinaryFormat(ext) } };
      counts.binaryFiles++;
      onEvent({ type: 'file_read', phase: 2, message: `binary: ${relativePath}`, filePath: relativePath, count: done, total });
      continue;
    }
    if (result.error !== null) {
      fileRecords[relativePath] = { ...record, extraction: { type: 'error', message: result.error, code: null } };
      counts.errorFiles++;
      onEvent({ type: 'file_error', phase: 2, message: `error reading ${relativePath}: ${result.error}`, filePath: relativePath, count: done, total });
      continue;
    }

    const text = result.text;
    const firstLines = text.split('\n').slice(0, 10).join('\n');

    // Check for generated markers in content
    if (baseClass === 'generated_candidate' || isGeneratedPath(relativePath) || relativePath.endsWith('.d.ts')) {
      const genCheck = detectGeneratedMarker(firstLines);
      if (genCheck.isGenerated || isGeneratedPath(relativePath) || relativePath.endsWith('.d.ts')) {
        const generator = detectGenerator(relativePath, firstLines);
        const sourceSpec: string | null = null;
        fileRecords[relativePath] = { ...record, extraction: { type: 'generated', generator, sourceSpec } };
        counts.generatedFiles++;
        onEvent({ type: 'file_read', phase: 2, message: `generated: ${relativePath}${generator ? ` (${generator})` : ''}`, filePath: relativePath, count: done, total });
        continue;
      }
    }

    // Check any file's first lines for generated markers (generated files can be anywhere)
    if (baseClass === 'source') {
      const genCheck = detectGeneratedMarker(firstLines);
      if (genCheck.isGenerated) {
        const generator = detectGenerator(relativePath, firstLines);
        fileRecords[relativePath] = { ...record, extraction: { type: 'generated', generator, sourceSpec: null } };
        counts.generatedFiles++;
        onEvent({ type: 'file_read', phase: 2, message: `generated: ${relativePath}`, filePath: relativePath, count: done, total });
        continue;
      }
    }

    let extraction: FileExtraction;

    switch (baseClass) {
      case 'source': {
        extraction = extractSource(text, record.language);
        break;
      }
      case 'schema': {
        const capped = text.slice(0, CONTENT_CAP_BYTES);
        extraction = { type: 'schema', content: capped };
        onEvent({ type: 'discovery_finding', phase: 2, message: `schema: ${relativePath}`, filePath: relativePath });
        break;
      }
      case 'config': {
        const capped = text.slice(0, CONTENT_CAP_BYTES);
        extraction = { type: 'config', content: capped };
        // Populate monorepo package names from package.json
        if (record.name === 'package.json') {
          fillMonorepoPackageName(relativePath, capped, monorepoPackages);
        }
        break;
      }
      case 'docs': {
        const capped = text.slice(0, CONTENT_CAP_BYTES);
        extraction = { type: 'docs', content: capped };
        break;
      }
      case 'script': {
        const capped = text.slice(0, CONTENT_CAP_BYTES);
        extraction = { type: 'script', content: capped };
        break;
      }
      default: {
        extraction = extractSource(text, record.language);
        break;
      }
    }

    fileRecords[relativePath] = { ...record, extraction };

    onEvent({ type: 'file_read', phase: 2, message: relativePath, filePath: relativePath, count: done, total });
  }

  return counts;
}

// ─── Monorepo Package Name Population ────────────────────────────────────────

function fillMonorepoPackageName(
  manifestRelativePath: string,
  content: string,
  monorepoPackages: MonorepoPackage[],
): void {
  try {
    const parsed = JSON.parse(content) as Record<string, unknown>;
    const name = typeof parsed['name'] === 'string' ? parsed['name'] : null;
    if (!name) return;
    const pkg = monorepoPackages.find(p => p.manifestPath === manifestRelativePath);
    if (pkg) pkg.name = name;
  } catch { /* non-fatal */ }
}

